#Numpy Implementation

In [1]:
import numpy as np
# Create a 2D Numpy array of size 1x3 with elements of your choice
arr1=np.array([[6,9,4]])
print(arr1)
# Create a Numpy array of length 50 with zeroes as its elements
arr2=np.zeros(50)
print(arr2)
#Create a Numpy array of length 3x2 with elements of your choice
arr3=np.array([[1,2],[3,4],[5,6]])
print(arr3)

arr4=np.matrix(arr1)*np.matrix(arr3)
print(arr4)

#Change 5th element of arr2 to a different number
#Your code here
arr2[4]=22
if np.shape(arr4)==(1,2) and arr2[4]!=0:
  print("Passed")
else:
  print("Fail")

[[6 9 4]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[[1 2]
 [3 4]
 [5 6]]
[[53 72]]
Passed


In [ ]:
import numpy as np

#Task: Perform the dot product of I and 9I+1 using numpy, here I is referred to as an 3x3 Identity matrix.
a=np.eye(3)
b=9*np.eye(3)+1
print(np.dot(a,b))

#Pandas Implementation

In [ ]:
import pandas as pd

## Create a DataFrame from a dictionary
data = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, 30, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}
#Your code here
df=pd.DataFrame(data)

#Display the first 2 rows of the data frame
#Your code here
print(df.head(2))

#Display the last 2 rows of the data frame
#Your code here
print(df.tail(2))

#Print the age column
#Your code here
print(df['Age'])

#Filter rows where age is greater than 26
#Your code here
age26=df[df['Age']>26]
print(age26)

#Add a new column 'Country' with the value 'India' for all rows
#Your code here
df=df.assign(Country='India')
print(df)

#Drop the 'City' column
#Your code here
df=df.drop('City', axis=1)
print(df)

data1 = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, None, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}

df2= pd.DataFrame(data1)

# Fill missing values in the 'Age' column with the mean age
#Your code here
avg=df2['Age'].mean()
#df2['Age'].replace(None, avg, inplace=True, regex=False)... don't know why this didn't work
df2['Age']=df2['Age'].fillna(avg)
print(df2)

#Matplotlib implementation

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


xpoints=np.array([1,2,3,4])
ypoints=np.array([2,4,6,8])

#Plot these points without draimportwing a line
#Your code here
plt.plot(xpoints,ypoints,'o')
plt.show()

#Plotting with marker: Plot these points with a marker(Star marker)
#Your code here
plt.plot(xpoints,ypoints,'*')
plt.show()

#Using fmt format, add circular marker,red color and Dashed line
#Your code here
plt.plot(xpoints,ypoints,'ro--')
plt.show()

#Add xlabel,ylabel and title for the plot.
#Your code here
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('Plot')
plt.plot(xpoints,ypoints,'ro--')
plt.show()

#Create a scatter plot for xpoints and ypoints
#Your code here
plt.scatter(xpoints, ypoints)
plt.show()

#Set color to the scatter plot. Blue,Green,Red and yellow color for each point respectively
plt.scatter(xpoints[0], ypoints[0], color='b')
plt.scatter(xpoints[1], ypoints[1], color='g')
plt.scatter(xpoints[2], ypoints[2], color='r')
plt.scatter(xpoints[3], ypoints[3], color='y')
plt.show()

# Miscellaneous Modules Implementation


In [ ]:
import random
import numpy as np

#Set the seed of random to 20
#Your code here
random.seed(20)
arr1=np.array([1,24,31,45,73,81,94,25])

#Using the random module pick 4 different random numbers from arr1 and return their sum.
#Your code here
sum=0
for x in range(5):
  y=random.choice(arr1)
  print(y)
  sum=sum+y
print("sum=",sum)